### ISSUE TITLE
Trouble with publishing to saas

### ISSUE THREAD

**Issue by lktraser** [microsoft/navcontainerhelper#1683]
**Describe the issue**
Hi Freddy, I'm having some trouble with your most recent blob posts on the new SAAS functionality of bccontainerhelper.
In [this](https://freddysblog.com/2021/01/24/bccontainerhelper-version-2-0-1/) entry you mention a function Publish-AppToBcContainer. This function is not published by bccontainerhelper and I can also not find it in the code I'm guessing you meant Publish-BcContainerApp. The bigger issue is that when I try to use your example to publish into a sandboxes development scope [like so](https://freddysblog.com/2021/01/27/publishing-apps-to-a-business-central-online-environment/) it errors that I don't have a container 'bcserver' which I assume is the default containername. The example makes it look like I shouldn't need a container for this tho. Whats going on here?

**Scripts used to create container and cause the issue**
```
$authContext = New-BcAuthContext -refreshToken $refreshToken
$environment = "Sandbox"

$apps = "https://businesscentralapps.azureedge.net/githubhelloworld/latest/apps.zip"
Publish-BcContainerApp `
    -bcAuthContext $authcontext `
    -environment $environment `
    -appFile $apps
```

**Full output of scripts**
```
Error: No such container: bcserver
ScriptHalted
In C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.5\ContainerHandling\Invoke-ScriptInNavContainer.ps1:112 Zeichen:17
+                 throw
+                 ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
```

Regards Leon

**Comment by freddydk** [comment]
The Publish-AppToBcContainer was a typo - fixed now.
Your script is correct, and works just fine without a container here:

```
$authContext = New-BcAuthContext -refreshToken $BcSaasRefreshTokenSecret.SecretValueText
$environment = "Sand3"

$apps = "https://businesscentralapps.azureedge.net/githubhelloworld/latest/apps.zip"
Publish-BcContainerApp `
    -bcAuthContext $authcontext `
    -environment $environment `
    -appFile $apps
```
gives this output and works fine.
```
Attempting authentication to https://api.businesscentral.dynamics.com/Common using refresh token...
Authenticated using refresh token as user Freddy Kristiansen (freddyk@demo.onmicrosoft.com)
Authenticated to common, using tenant id 69cb4a05-45a8-412d-9f33-10fb5cf7db05
Downloading C:\Users\freddyk\AppData\Local\Temp\65b9e841-e211-4fbb-ad37-f490ebc51ee3
Publishing Default Publisher_Default Base App Name_2.0.32.0.app to https://api.businesscentral.dynamics.com/v2.0/Sand3/dev/apps?SchemaUpdateMode=synchronize
App Default Publisher_Default Base App Name_2.0.32.0.app successfully published
Publishing Default Publisher_Default App Name_2.0.32.0.app to https://api.businesscentral.dynamics.com/v2.0/Sand3/dev/apps?SchemaUpdateMode=synchronize
App Default Publisher_Default App Name_2.0.32.0.app successfully published
```
Did you use other parameters? 
or maybe an older version of BcContainerHelper?

**Comment by lktraser** [comment]
I ran
````
Uninstall-Module bccontainerhelper -AllVersions -Force
Install-Module bccontainerhelper -Repository PSGallery -AllowPrerelease
````
Then ran, again now everything works as planned. But as you can see in my first output I was running 2.0.5. 
I'm really not sure what was going on there. But thanks for the fix 👍

**Comment by lktraser** [comment]
Sadly I closed this prematurely. The problem still persists within my pipeline the difference is that I don't download a zip there but feed a string array of appfiles into it. 
```
[string[]]$apps = Get-ChildItem $(System.ArtifactsDirectory) -Recurse -filter "*_SAAS.app" -Exclude "*Test*"
```
$apps contains 2 paths to app files. This leeds to the previous problem.
```
Error: No such container: bcserver
ScriptHalted
In C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.5\ContainerHandling\Invoke-ScriptInNavContainer.ps1:112 Zeichen:17
+                 throw
+                 ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
```

**Comment by freddydk** [comment]
I will have a look

**Comment by freddydk** [comment]
I still cannot repro this, what is the full script you are running? what is the full output?

The only reasons I can see why Publish-BcContainerApp would need a containername is if:
1. BcAuthContext or Environment is not set
2. ShowMyCode, replaceDependencies or replacepackageid is set

**Comment by lktraser** [comment]
I recompiled my apps and made sure they were showmycode = false. The publish works now. 
So I tried to also publish my test app. To do so I tried the new testtoolkit import.
```
Import-TestToolkitToBcContainer -bcAuthContext $authcontext -environment 'cicd'
```
I can publish with the same $authcontext and environment but on this I get:
```
Error: No such object: bcserver
Import-TestToolkitToBcContainer : Die Eigenschaft "Config" wurde für dieses Objekt nicht gefunden. Vergewissern Sie sich, dass die 
Eigenschaft vorhanden ist.
In Zeile:1 Zeichen:1
+ Import-TestToolkitToBcContainer -bcAuthContext $authcontext -environm ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-TestToolkitToBcContainer], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Import-TestToolkitToBcContainer
```

**Comment by freddydk** [comment]
I really really really like to get full scripts and full output - it takes a lot of time for me to guess what you are doing.

**Comment by lktraser** [comment]
Sure, sorry if I've not been clear enough.
```
$authcontext = New-BcAuthContext -refreshToken $refreshToken
Import-TestToolkitToBcContainer -bcAuthContext $authcontext -environment 'cicd'
```

```
BcContainerHelper version 2.0.5-preview342
Attempting authentication to https://api.businesscentral.dynamics.com/Common using refresh token...
Authenticated using refresh token as user ***
Authenticated to common, using tenant id ***
docker : Error: No such object: bcserver
In C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.5\ObjectHandling\Import-TestToolkitToNavContainer.ps1:86 Zeichen:16
+     $inspect = docker inspect $containerName | ConvertFrom-Json
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: No such object: bcserver:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
Hope this helps

**Comment by freddydk** [comment]
Import-TestToolkitToBcContainer uses the Install-BcAppFromAppSource function to install the test toolkit, and as explained here:
https://freddysblog.com/2021/01/27/publishing-apps-to-a-business-central-online-environment/ that one needs a container (it can be a files only container) until the functionality is added to the admin center API.
I am documenting my way through these things and there will be a blog post on running tests in online environments with this information as well.

**Comment by lktraser** [comment]
Alright, I'll probably wait for the admin center API integration then. My initial problem is solved, sorry for going off topic. Thanks for the support.
