### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

### ISSUE THREAD

**Issue by sirhc101** [microsoft/navcontainerhelper#1877]
**Describe the issue**
Since a few days some of my build pipelines crashing due to an exception `Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'`. 

The weird thing is, that from overall 16 pipelines only 4 are failing. All using the same pipeline definition and scripts. I looked into it but cannot find any difference or reason. It only occurs using the `Next Major` image

**Scripts used to create container and cause the issue**
```
Write-Host "Artifacts: $artifact"
if ($artifact -like 'https://*') {
    $artifactUrl = $artifact
    if ($sasToken) {
        $artifactUrl += $sasToken
    }
}
else {
    $segments = "$artifact/////".Split('/')

    if ($segments[0] -eq "bcinsider") {
        Write-Host "Using bcinsider storage account.";
        $artifactUrl = Get-BCArtifactUrl -storageAccount $segments[0] -type $segments[1] -version $segments[2] -country $segments[3] -select $segments[4] -sasToken $sasToken | Select-Object -First 1
    } else {
        Write-Host "Using bcartifacts storage account.";
        $artifactUrl = Get-BCArtifactUrl -storageAccount $segments[0] -type $segments[1] -version $segments[2] -country $segments[3] -select $segments[4] | Select-Object -First 1
    }
     
    if (-not ($artifactUrl)) {
        throw "Unable to locate artifactUrl from $artifact"
    }
}

if (-not ($credential)) {
    $securePassword = try { $ENV:PASSWORD | ConvertTo-SecureString } catch { ConvertTo-SecureString -String $ENV:PASSWORD -AsPlainText -Force }
    $credential = New-Object PSCredential -ArgumentList $ENV:USERNAME, $SecurePassword
}

if (-not ($licenseFile)) {
    $licenseFile = try { $ENV:LICENSEFILE | ConvertTo-SecureString } catch { ConvertTo-SecureString -String $ENV:LICENSEFILE -AsPlainText -Force }
}

Write-Host "Create $containerName from $($artifactUrl.split('?')[0])"

$parameters = @{
    "Accept_Eula" = $true
    "Accept_Outdated" = $true
}

if ($licenseFile) {
    $unsecureLicenseFile = ([System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($licenseFile)))
    $parameters += @{
        "licenseFile" = $unsecureLicenseFile
    }
}

if ($buildenv -eq "Local") {
    $workspaceFolder = (Get-Item (Join-Path $PSScriptRoot "..")).FullName
    $additionalParameters = @("--volume ""${workspaceFolder}:C:\Source""") 
}
elseif ($buildenv -eq "AzureDevOps") {
    $segments = "$PSScriptRoot".Split('\')
    $rootFolder = "$($segments[0])\$($segments[1])"
    $additionalParameters = @("--volume ""$($rootFolder):C:\Agent""")
    $parameters += @{ 
        "shortcuts" = "None"
    }
}
else {
    $workspaceFolder = (Get-Item (Join-Path $PSScriptRoot "..")).FullName
    $additionalParameters = @("--volume ""C:\DEMO:C:\DEMO""")
    $parameters += @{ 
        "shortcuts" = "None"
        "useTraefik" = $true
        "myscripts" = @(@{ "AdditionalOutput.ps1" = "copy-item -Path 'C:\Run\*.vsix' -Destination 'C:\ProgramData\bccontainerhelper\Extensions\$containerName' -force" })
    }
}

$restoreDb = $reuseContainer -and (Test-BCContainer -containerName $containerName)
if ($restoreDb) {
    try {
        Restore-DatabasesInBCContainer -containerName $containerName -bakFolder $containerName
        Invoke-ScriptInBCContainer -containerName $containerName -scriptBlock { Param([pscredential]$credential)
            $user = Get-NAVServerUser -ServerInstance $ServerInstance | Where-Object { $_.Username -eq $credential.UserName }
            if ($user) {
                Write-Host "Setting Password for user: $($credential.UserName)"
                Set-NavServerUser -ServerInstance $ServerInstance -UserName $credential.UserName -Password $credential.Password
            }
            else {
                Write-Host "Creating user: $($credential.UserName)"
                New-NavServerUser -ServerInstance $ServerInstance -UserName $credential.UserName -Password $credential.Password
                New-NavServerUserPermissionSet -ServerInstance $ServerInstance -UserName $credential.UserName -PermissionSetId "SUPER"
            }
        } -argumentList $credential
    }
    catch {
        $restoreDb = $false
    }
}
if ($imageName) {
    $parameters += @{ "imageName" = $imageName }
}
if (!$restoreDb) {
    New-BCContainer @Parameters `
                    -doNotCheckHealth `
                    -updateHosts `
                    -containerName $containerName `
                    -artifactUrl $artifactUrl `
                    -auth "UserPassword" `
                    -Credential $credential `
                    -additionalParameters $additionalParameters `
                    -doNotUseRuntimePackages `
                    -enableTaskScheduler:$false `
                    -multitenant:$false
    
    Import-TestToolkitToBCContainer `
        -containerName $containerName `
        -Credential $credential `
        -includeTestLibrariesOnly

    if ($reuseContainer) {
        Backup-BCContainerDatabases -containerName $containerName -bakFolder $containerName
    }
}
```

**Full output of scripts**
```
2021-04-08T02:55:23.9020093Z Artifacts: bcinsider/sandbox//de/Latest
2021-04-08T02:55:23.9069213Z Using bcinsider storage account.
2021-04-08T02:55:24.1024251Z BcContainerHelper version 2.0.10
2021-04-08T02:55:26.3034742Z Create nextmajor-businessdevsrv02 from https://bcinsider.azureedge.net/sandbox/19.0.24102.0/de
2021-04-08T02:55:26.4355449Z WARNING: Container name should not exceed 15 characters
2021-04-08T02:55:27.2468316Z BcContainerHelper is version 2.0.10
2021-04-08T02:55:27.2475900Z BcContainerHelper is running as ***istrator
2021-04-08T02:55:27.2488626Z Host is Microsoft Windows Server 2019 Standard - ltsc2019
2021-04-08T02:55:27.3653647Z Docker Client Version is 19.03.5
2021-04-08T02:55:27.3665825Z Docker Server Version is 19.03.5
2021-04-08T02:55:27.6622246Z Fetching all docker images
2021-04-08T02:55:27.8062362Z Fetching all docker volumes
2021-04-08T02:55:27.8957314Z ArtifactUrl and ImageName specified
2021-04-08T02:55:28.0385849Z Image nextmajor:sandbox-19.0.24102.0-de already exists
2021-04-08T02:55:28.3250985Z Using image nextmajor:sandbox-19.0.24102.0-de
2021-04-08T02:55:28.4226470Z Disabling Health Check (always report healthy)
2021-04-08T02:55:28.4307982Z Creating Container nextmajor-businessdevsrv02
2021-04-08T02:55:28.4430292Z Version: 19.0.24102.0-DE
2021-04-08T02:55:28.4438261Z Style: sandbox
2021-04-08T02:55:28.4446394Z Multitenant: No
2021-04-08T02:55:28.4454158Z Platform: 18.0.24035.0
2021-04-08T02:55:28.4459715Z Generic Tag: 1.0.1.4
2021-04-08T02:55:28.4476627Z Container OS Version: 10.0.17763.1697 (ltsc2019)
2021-04-08T02:55:28.4480973Z Host OS Version: 10.0.17763.1697 (ltsc2019)
2021-04-08T02:55:28.4509630Z Using process isolation
2021-04-08T02:55:28.4547994Z Using locale de-DE
2021-04-08T02:55:28.4573191Z Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
2021-04-08T02:55:28.4682824Z Using license file https://www.dropbox.com/s/ul8nqiw74n6y6xk/bc.license.flf
2021-04-08T02:55:28.4783901Z Downloading C:\ProgramData\BcContainerHelper\Extensions\nextmajor-businessdevsrv02\my\license.flf
2021-04-08T02:55:30.3287240Z Additional Parameters:
2021-04-08T02:55:30.3306821Z --volume "C:\agent:C:\Agent"
2021-04-08T02:55:30.3316863Z --env customNavSettings=EnableTaskScheduler=False
2021-04-08T02:55:30.3325373Z Files in C:\ProgramData\BcContainerHelper\Extensions\nextmajor-businessdevsrv02\my:
2021-04-08T02:55:30.3453725Z - AdditionalOutput.ps1
2021-04-08T02:55:30.3461548Z - license.flf
2021-04-08T02:55:30.3466854Z - MainLoop.ps1
2021-04-08T02:55:30.3471255Z - SetupVariables.ps1
2021-04-08T02:55:30.3475507Z - updatehosts.ps1
2021-04-08T02:55:30.3479827Z Creating container nextmajor-businessdevsrv02 from image nextmajor:sandbox-19.0.24102.0-de
2021-04-08T02:55:30.7418847Z 89ae4d227753e82442f13e6ee8e077bf25f9fedd85317f6f328a6ffb4772952c
2021-04-08T02:55:35.6889562Z Waiting for container nextmajor-businessdevsrv02 to be ready
2021-04-08T02:55:43.5080828Z Adding NEXTMAJOR-BUSIN to hosts file
2021-04-08T02:55:43.5087484Z Initializing...
2021-04-08T02:55:43.5092207Z Setting host.containerhelper.internal to 51.75.147.254 in container hosts file (copy from host hosts file)
2021-04-08T02:55:43.5096987Z Starting Container
2021-04-08T02:55:43.5100770Z Hostname is nextmajor-businessdevsrv02
2021-04-08T02:55:44.6105862Z PublicDnsName is nextmajor-businessdevsrv02
2021-04-08T02:55:44.6113315Z Using NavUserPassword Authentication
2021-04-08T02:55:47.9130948Z Starting Local SQL Server
2021-04-08T02:55:50.1131888Z Starting Internet Information Server
2021-04-08T02:55:52.3297231Z Creating Self Signed Certificate
2021-04-08T02:55:52.3304303Z Self Signed Certificate Thumbprint 88028C2C8C5153F0D15960A93789A11BFA387735
2021-04-08T02:55:52.3308668Z Modifying Service Tier Config File with Instance Specific Settings
2021-04-08T02:55:52.3312686Z Modifying Service Tier Config File with settings from environment variable
2021-04-08T02:55:53.4328746Z Setting EnableTaskScheduler to False
2021-04-08T02:58:01.6398749Z Starting Service Tier
2021-04-08T02:58:02.7395444Z Registering event sources
2021-04-08T02:58:24.4931833Z Creating DotNetCore Web Server Instance
2021-04-08T02:58:24.4936846Z Enabling Financials User Experience
2021-04-08T02:58:24.4941096Z Using license file 'c:\run\my\license.flf'
2021-04-08T02:58:26.7393877Z Import License
2021-04-08T02:58:29.0149875Z Creating http download site
2021-04-08T02:58:30.1115660Z Setting SA Password and enabling SA
2021-04-08T02:58:30.1123042Z Creating *** as SQL User and add to sys***
2021-04-08T02:58:31.2101462Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:32.3086729Z Creating SUPER user
2021-04-08T02:58:38.9907302Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:40.1310134Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:40.1315628Z Container IP Address: 172.22.197.238
2021-04-08T02:58:40.1321881Z Container Hostname  : nextmajor-businessdevsrv02
2021-04-08T02:58:40.1327297Z Container Dns Name  : nextmajor-businessdevsrv02
2021-04-08T02:58:40.1332193Z Web Client          : http://nextmajor-businessdevsrv02/BC/
2021-04-08T02:58:40.1337506Z Dev. Server         : http://nextmajor-businessdevsrv02
2021-04-08T02:58:40.1342157Z Dev. ServerInstance : BC
2021-04-08T02:58:40.1347546Z Setting nextmajor-businessdevsrv02 to 172.22.197.238 in host hosts file
2021-04-08T02:58:40.1349958Z 
2021-04-08T02:58:40.1355334Z Files:
2021-04-08T02:58:40.1360766Z http://nextmajor-businessdevsrv02:8080/ALLanguage.vsix
2021-04-08T02:58:40.1363568Z 
2021-04-08T02:58:40.1369010Z WARNING: You are running a container which is 84 days old.
2021-04-08T02:58:40.1374729Z Microsoft recommends that you always run the latest version of our containers.
2021-04-08T02:58:40.1377553Z 
2021-04-08T02:58:40.1382446Z Container Total Physical Memory is 31.7Gb
2021-04-08T02:58:40.1388341Z Container Free Physical Memory is 24.1Gb
2021-04-08T02:58:40.1390810Z 
2021-04-08T02:58:40.1397074Z Initialization took 177 seconds
2021-04-08T02:58:40.1402118Z Ready for connections!
2021-04-08T02:58:40.1407560Z Reading CustomSettings.config from nextmajor-businessdevsrv02
2021-04-08T02:58:44.7139500Z Container nextmajor-businessdevsrv02 successfully created
2021-04-08T02:58:44.7142162Z 
2021-04-08T02:58:44.7150429Z Use:
2021-04-08T02:58:44.7156238Z Get-BcContainerEventLog -containerName nextmajor-businessdevsrv02 to retrieve a snapshot of the event log from the container
2021-04-08T02:58:44.7161219Z Get-BcContainerDebugInfo -containerName nextmajor-businessdevsrv02 to get debug information about the container
2021-04-08T02:58:44.7168532Z Enter-BcContainer -containerName nextmajor-businessdevsrv02 to open a PowerShell prompt inside the container
2021-04-08T02:58:44.7175715Z Remove-BcContainer -containerName nextmajor-businessdevsrv02 to remove the container again
2021-04-08T02:58:44.7182869Z docker logs nextmajor-businessdevsrv02 to retrieve information about URL's again
2021-04-08T02:58:45.8553129Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:46.0884621Z Synchronizing Test Runner on default
2021-04-08T02:58:46.4813448Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:48.2279332Z App successfully synchronized
2021-04-08T02:58:48.2409245Z Installing Test Runner on default
2021-04-08T02:58:48.2483428Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:50.6766799Z App successfully installed
2021-04-08T02:58:50.6929304Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:50.7143930Z Synchronizing Any on default
2021-04-08T02:58:50.7299144Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:50.7400773Z App successfully synchronized
2021-04-08T02:58:50.7460007Z Installing Any on default
2021-04-08T02:58:50.7514068Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:50.8458518Z App successfully installed
2021-04-08T02:58:50.8595162Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:50.8726618Z Synchronizing Library Assert on default
2021-04-08T02:58:50.8898661Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:50.9000883Z App successfully synchronized
2021-04-08T02:58:50.9054930Z Installing Library Assert on default
2021-04-08T02:58:50.9119505Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:50.9937780Z App successfully installed
2021-04-08T02:58:51.0058922Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:51.0156604Z Skipping app 'C:\Applications.DE\Microsoft_Permissions Mock_19.0.24102.0.app' as it is already installed
2021-04-08T02:58:51.0287808Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:51.0416530Z Synchronizing Library Variable Storage on default
2021-04-08T02:58:51.0595838Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:51.0666061Z App successfully synchronized
2021-04-08T02:58:51.0721034Z Installing Library Variable Storage on default
2021-04-08T02:58:51.0778398Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:51.1546580Z App successfully installed
2021-04-08T02:58:51.1732328Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:51.9363008Z Publishing C:\ProgramData\BcContainerHelper\Extensions\nextmajor-businessdevsrv02\a3447e73-fcd0-4cc0-bf49-e403b2d96ec8\Microsoft_System Application Test Library_19.0.24102.0.runtime.app
2021-04-08T02:58:51.9463616Z WARNING: This license is not compatible with this version of Business Central.
2021-04-08T02:58:51.9551031Z WARNING: UnhandledErrorMessage
2021-04-08T02:58:51.9947722Z Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
2021-04-08T02:58:51.9955805Z at <ScriptBlock>, <No file>: line 18
2021-04-08T02:58:51.9965640Z at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
2021-04-08T02:58:51.9969880Z at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\AppHandling\Publish-NavContainerApp.ps1: line 257
2021-04-08T02:58:51.9974019Z at Publish-BcContainerApp, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\AppHandling\Publish-NavContainerApp.ps1: line 117
2021-04-08T02:58:51.9978225Z at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 185
2021-04-08T02:58:51.9983164Z at Import-TestToolkitToBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 153
2021-04-08T02:58:51.9987889Z at <ScriptBlock>, C:\agent\_work\458\s\businessdev.BC.Pipeline\ps\Create-Container.ps1: line 135
2021-04-08T02:58:51.9991986Z at <ScriptBlock>, C:\agent\_work\_temp\9e917dbf-d466-48fa-b193-15b839bf201a.ps1: line 3
2021-04-08T02:58:51.9996030Z at <ScriptBlock>, <No file>: line 1
2021-04-08T02:58:52.1582454Z ##[error]Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' 
or one of its dependencies. The system cannot find the file specified.
At C:\Program 
Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\ContainerHandling\Invoke-ScriptInNavContainer.ps1:45 char:13
+             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not load ...file specified.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, Pub 
   licKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
2021-04-08T02:58:52.1606530Z ##[error]PowerShell exited with code '1'.
```

**Comment by freddydk** [comment]
I fixed that a few days ago in the preview

**Comment by MatthewMcCarthy7** [comment]
I'm still getting this issue, and I'm on the newest version. BcContainerHelper is version 2.0.11-preview422

**Comment by freddydk** [comment]
Could you display the full output of the script when running 2.0.11-preview422?

**Comment by MatthewMcCarthy7** [comment]
2021-04-19T15:23:52.0698898Z ##[section]Starting: Run Pipeline
2021-04-19T15:23:52.0928911Z ==============================================================================
2021-04-19T15:23:52.0929698Z Task         : PowerShell
2021-04-19T15:23:52.0930346Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2021-04-19T15:23:52.0930958Z Version      : 2.180.1
2021-04-19T15:23:52.0931513Z Author       : Microsoft Corporation
2021-04-19T15:23:52.0932286Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2021-04-19T15:23:52.0933176Z ==============================================================================
2021-04-19T15:23:53.9217874Z Generating script.
2021-04-19T15:23:53.9333797Z Formatted command: . 'C:\Agent\_work\24\s\DevOpsBCScripts\DevOps-Pipeline.ps1' -environment "AzureDevOps" -version "nextmajor" -appBuild 900014 -appRevision 0 -buildProjectFolder SWE -appSettingFile \.DevOps\App-settings.json
2021-04-19T15:23:54.0116016Z ========================== Starting Command Output ===========================
2021-04-19T15:23:54.0685261Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\Agent\_work\_temp\35d353da-7e3f-4b71-b5e9-090822f52202.ps1'"
2021-04-19T15:23:54.7791468Z Set artifact = ///us/NextMajor/{INSIDERSASTOKEN}
2021-04-19T15:23:54.7850806Z Set pipelineName = SWE-nextmajor
2021-04-19T15:23:54.7973237Z Set containerName = devops2-SWE-nextmajor
2021-04-19T15:23:54.9295031Z Set Code Sign License File = C:\License\BCCodeSign.pfx
2021-04-19T15:23:54.9309100Z Set Code Sign Default Password
2021-04-19T15:23:54.9337131Z Set Insider Token
2021-04-19T15:23:54.9361971Z Set installApps = 'C:\Agent\_work\24\s\SWE\SWE-WI\InstallApps\Insight Works_IWorks Common_2.4.7674.0_runtime 18.0.app,C:\Agent\_work\24\s\SWE\SWE-WI\InstallApps\Insight Works_Warehouse Insight Advanced WMS_2.4.7684.0_runtime 18.0.app'
2021-04-19T15:23:54.9377941Z Set previousApps = 'C:\Agent\_work\24\s\SWE\SWE-Base\.alpackages\Silverware Inc._Silver Leaf SWE_1.4.10061.0.app'
2021-04-19T15:23:54.9393678Z Set appSourceCopMandatoryAffixes = 'SWE,SWE-TT,SWE-CU'
2021-04-19T15:23:54.9407231Z Set appSourceCopSupportedCountries = 'us'
2021-04-19T15:23:54.9421401Z Set appFolders = 'SWE-Base,SWE-TT,SWE-CU,SWE-WI'
2021-04-19T15:23:54.9435866Z Set testFolders = 'SWE-Test'
2021-04-19T15:23:54.9450343Z Set memoryLimit = '6G'
2021-04-19T15:23:54.9464761Z Set additionalCountries = ''
2021-04-19T15:23:54.9479171Z Set genericImageName = ''
2021-04-19T15:23:54.9492931Z Set vaultNameForLocal = 'BuildVariables'
2021-04-19T15:23:54.9506717Z Set bcContainerHelperVersion = 'preview'
2021-04-19T15:23:54.9522336Z Set rulesetFile = 'C:\Agent\_work\24\s\SWE\.DevOps\SWE.ruleset.json'
2021-04-19T15:23:54.9536646Z Set installTestRunner = False
2021-04-19T15:23:54.9552166Z Set installTestFramework = True
2021-04-19T15:23:54.9607793Z Set installTestLibraries = True
2021-04-19T15:23:54.9671488Z Set installPerformanceToolkit = False
2021-04-19T15:23:54.9736379Z Set enableCodeCop = False
2021-04-19T15:23:54.9799006Z Set enableAppSourceCop = False
2021-04-19T15:23:54.9867406Z Set enablePerTenantExtensionCop = False
2021-04-19T15:23:54.9929232Z Set enableUICop = True
2021-04-19T15:23:54.9994577Z Set useDefaultAppSourceRuleSet = True
2021-04-19T15:23:55.0058551Z Set doNotSignApps = False
2021-04-19T15:23:55.0120823Z Set doNotRunTests = False
2021-04-19T15:23:55.0144211Z Set cacheImage = False
2021-04-19T15:23:55.0167415Z Set CreateRuntimePackages = False
2021-04-19T15:23:57.0100659Z BcContainerHelper version 2.0.11-preview422
2021-04-19T15:23:59.1676772Z Determining artifacts to use
2021-04-19T15:24:45.0789757Z   _____                               _                
2021-04-19T15:24:45.0804052Z  |  __ \                             | |               
2021-04-19T15:24:45.0819269Z  | |__) |_ _ _ __ __ _ _ __ ___   ___| |_ ___ _ __ ___ 
2021-04-19T15:24:45.0834807Z  |  ___/ _` | '__/ _` | '_ ` _ \ / _ \ __/ _ \ '__/ __|
2021-04-19T15:24:45.0850035Z  | |  | (_| | | | (_| | | | | | |  __/ |_  __/ |  \__ \
2021-04-19T15:24:45.0864177Z  |_|   \__,_|_|  \__,_|_| |_| |_|\___|\__\___|_|  |___/
2021-04-19T15:24:45.0873037Z 
2021-04-19T15:24:45.0887414Z Pipeline name               SWE-nextmajor
2021-04-19T15:24:45.0901449Z Container name              devops2-SWE-nextmajor
2021-04-19T15:24:45.0916083Z Image name                  
2021-04-19T15:24:45.0931707Z ArtifactUrl                 https://bcinsider.azureedge.net/sandbox/19.0.24563.0/us
2021-04-19T15:24:45.0945765Z SasToken                    Specified
2021-04-19T15:24:45.0969933Z BcAuthContext               Not Specified
2021-04-19T15:24:45.0993383Z Environment                 
2021-04-19T15:24:45.1022484Z ReUseContainer              False
2021-04-19T15:24:45.1051851Z KeepContainer               False
2021-04-19T15:24:45.1438465Z Credential                  admin/Qulo4935
2021-04-19T15:24:45.1502611Z MemoryLimit                 6G
2021-04-19T15:24:45.1533682Z Enable Task Scheduler       False
2021-04-19T15:24:45.1563375Z Assign Premium Plan         False
2021-04-19T15:24:45.1592969Z Install Test Runner         False
2021-04-19T15:24:45.1622880Z Install Test Framework      True
2021-04-19T15:24:45.1652772Z Install Test Libraries      True
2021-04-19T15:24:45.1683846Z Install Perf. Toolkit       False
2021-04-19T15:24:45.1715588Z CopySymbolsFromContainer    False
2021-04-19T15:24:45.1747757Z enableCodeCop               False
2021-04-19T15:24:45.1778874Z enableAppSourceCop          False
2021-04-19T15:24:45.1809498Z enableUICop                 True
2021-04-19T15:24:45.1838190Z enablePerTenantExtensionCop False
2021-04-19T15:24:45.1866206Z escapeFromCops              False
2021-04-19T15:24:45.1895872Z useDefaultAppSourceRuleSet  True
2021-04-19T15:24:45.1922640Z rulesetFile                 C:\Agent\_work\24\s\SWE\.DevOps\SWE.ruleset.json
2021-04-19T15:24:45.1951954Z azureDevOps                 True
2021-04-19T15:24:45.1982562Z License file                Specified
2021-04-19T15:24:45.2013816Z CodeSignCertPfxFile         Specified
2021-04-19T15:24:45.2037525Z TestResultsFile             C:\Agent\_work\24\s\SWE\TestResults.xml
2021-04-19T15:24:45.2064270Z TestResultsFormat           JUnit
2021-04-19T15:24:45.2143490Z AdditionalCountries         
2021-04-19T15:24:45.2172750Z PackagesFolder              C:\Agent\_work\24\s\SWE\.packages
2021-04-19T15:24:45.2199264Z OutputFolder                C:\Agent\_work\24\s\SWE\.output
2021-04-19T15:24:45.2226212Z BuildArtifactFolder         C:\Agent\_work\24\a
2021-04-19T15:24:45.2254894Z CreateRuntimePackages       False
2021-04-19T15:24:45.2287222Z AppBuild                    900014
2021-04-19T15:24:45.2319953Z AppRevision                 0
2021-04-19T15:24:45.2334880Z Install Apps
2021-04-19T15:24:45.2359155Z - C:\Agent\_work\24\s\SWE\SWE-WI\InstallApps\Insight Works_IWorks Common_2.4.7674.0_runtime 18.0.app
2021-04-19T15:24:45.2373843Z - C:\Agent\_work\24\s\SWE\SWE-WI\InstallApps\Insight Works_Warehouse Insight Advanced WMS_2.4.7684.0_runtime 18.0.app
2021-04-19T15:24:45.2387514Z Install Test Apps
2021-04-19T15:24:45.2401491Z - None
2021-04-19T15:24:45.2415349Z Previous Apps
2021-04-19T15:24:45.2437037Z - C:\Agent\_work\24\s\SWE\SWE-Base\.alpackages\Silverware Inc._Silver Leaf SWE_1.4.10061.0.app
2021-04-19T15:24:45.2452089Z Application folders
2021-04-19T15:24:45.2479032Z - C:\Agent\_work\24\s\SWE\SWE-Base
2021-04-19T15:24:45.2493427Z - C:\Agent\_work\24\s\SWE\SWE-TT
2021-04-19T15:24:45.2507473Z - C:\Agent\_work\24\s\SWE\SWE-CU
2021-04-19T15:24:45.2521533Z - C:\Agent\_work\24\s\SWE\SWE-WI
2021-04-19T15:24:45.2535833Z Test application folders
2021-04-19T15:24:45.2558956Z - C:\Agent\_work\24\s\SWE\SWE-Test
2021-04-19T15:24:45.2664570Z RunTestsInBcContainer override
2021-04-19T15:24:45.2736093Z  Param([Hashtable]$parameters) Run-TestsInBcContainer -debugMode @parameters 
2021-04-19T15:24:45.2838515Z 
2021-04-19T15:24:45.2853610Z   _____       _ _ _                                          _        _                            
2021-04-19T15:24:45.2868348Z  |  __ \     | | (_)                                        (_)      (_)                           
2021-04-19T15:24:45.2883047Z  | |__) |   _| | |_ _ __   __ _    __ _  ___ _ __   ___ _ __ _  ___   _ _ __ ___   __ _  __ _  ___ 
2021-04-19T15:24:45.2898818Z  |  ___/ | | | | | | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '__| |/ __| | | '_ ` _ \ / _` |/ _` |/ _ \
2021-04-19T15:24:45.2915804Z  | |   | |_| | | | | | | | (_| | | (_| |  __/ | | |  __/ |  | | (__  | | | | | | | (_| | (_| |  __/
2021-04-19T15:24:45.2930674Z  |_|    \__,_|_|_|_|_| |_|\__, |  \__, |\___|_| |_|\___|_|  |_|\___| |_|_| |_| |_|\__,_|\__, |\___|
2021-04-19T15:24:45.2944740Z                            __/ |   __/ |                                                 __/ |     
2021-04-19T15:24:45.2959318Z                           |___/   |___/                                                 |___/      
2021-04-19T15:24:45.2966457Z 
2021-04-19T15:24:46.4353025Z Pulling mcr.microsoft.com/businesscentral:10.0.17763.1879
2021-04-19T15:40:19.8199837Z 
2021-04-19T15:40:19.8219951Z Pulling generic image took 935 seconds
2021-04-19T15:40:19.8331449Z 
2021-04-19T15:40:19.8346480Z    _____                _   _                               _        _                 
2021-04-19T15:40:19.8363623Z   / ____|              | | (_)                             | |      (_)                
2021-04-19T15:40:19.8379195Z  | |     _ __ ___  __ _| |_ _ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
2021-04-19T15:40:19.8394166Z  | |    | '__/ _ \/ _` | __| | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
2021-04-19T15:40:19.8408941Z  | |____| | |  __/ (_| | |_| | | | | (_| | | (__ (_) | | | | |_ (_| | | | | |  __/ |   
2021-04-19T15:40:19.8423617Z   \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|   
2021-04-19T15:40:19.8438356Z                                      __/ |                                             
2021-04-19T15:40:19.8453315Z                                     |___/                                              
2021-04-19T15:40:19.8461015Z 
2021-04-19T15:40:21.2139165Z WARNING: Container name should not exceed 15 characters
2021-04-19T15:40:22.4172645Z BcContainerHelper is version 2.0.11-preview422
2021-04-19T15:40:22.4187695Z BcContainerHelper is running as administrator
2021-04-19T15:40:22.4232870Z Host is Microsoft Windows Server 2019 Standard - ltsc2019
2021-04-19T15:40:22.9550357Z Docker Client Version is 19.03.5
2021-04-19T15:40:22.9595490Z Docker Server Version is 19.03.5
2021-04-19T15:40:24.1206617Z Fetching all docker images
2021-04-19T15:40:24.5593188Z Fetching all docker volumes
2021-04-19T15:40:25.4527226Z Using image mcr.microsoft.com/businesscentral:10.0.17763.1879
2021-04-19T15:40:25.9529750Z Creating Container devops2-SWE-nextmajor
2021-04-19T15:40:25.9543960Z Version: 19.0.24563.0-US
2021-04-19T15:40:25.9557583Z Style: sandbox
2021-04-19T15:40:25.9571795Z Multitenant: Yes
2021-04-19T15:40:25.9585352Z Platform: 18.0.24349.0
2021-04-19T15:40:25.9600317Z Generic Tag: 1.0.1.5
2021-04-19T15:40:25.9686362Z Container OS Version: 10.0.17763.1879 (ltsc2019)
2021-04-19T15:40:25.9701614Z Host OS Version: 10.0.17763.1879 (ltsc2019)
2021-04-19T15:40:25.9748390Z Using process isolation
2021-04-19T15:40:25.9828454Z Using locale en-US
2021-04-19T15:40:25.9867894Z Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
2021-04-19T15:40:26.0019037Z Using license file C:\License\SWBC.flf
2021-04-19T15:40:26.0755311Z Additional Parameters:
2021-04-19T15:40:26.0776961Z --volume "C:\Agent\_work\24\s\SWE:c:\sources"
2021-04-19T15:40:26.0790967Z --env customNavSettings=EnableTaskScheduler=False
2021-04-19T15:40:26.0806286Z Files in C:\ProgramData\BcContainerHelper\Extensions\devops2-SWE-nextmajor\my:
2021-04-19T15:40:26.0888847Z - AdditionalOutput.ps1
2021-04-19T15:40:26.0904894Z - license.flf
2021-04-19T15:40:26.0920890Z - MainLoop.ps1
2021-04-19T15:40:26.0936430Z - SetupVariables.ps1
2021-04-19T15:40:26.0951465Z - updatehosts.ps1
2021-04-19T15:40:26.0966525Z Creating container devops2-SWE-nextmajor from image mcr.microsoft.com/businesscentral:10.0.17763.1879
2021-04-19T15:40:26.8548336Z 4cfe96c5661bf145aaa4a0d552e60c485463c875cedb320fc0dcebfec9e6c8b1
2021-04-19T15:40:34.5297545Z Waiting for container devops2-SWE-nextmajor to be ready
2021-04-19T15:40:49.6133746Z Adding DEVOPS2-SWE-NEX to hosts file
2021-04-19T15:40:49.6148578Z Using artifactUrl https://bcinsider.azureedge.net/sandbox/19.0.24563.0/us
2021-04-19T15:40:51.0645534Z Using installer from C:\Run\150-new
2021-04-19T15:40:51.0660118Z Installing Business Central
2021-04-19T15:40:51.0674817Z Installing from artifacts
2021-04-19T15:41:01.7526442Z Starting Local SQL Server
2021-04-19T15:41:01.7544037Z WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
2021-04-19T15:41:04.6865049Z start...
2021-04-19T15:41:04.6881502Z WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
2021-04-19T15:41:04.6895784Z start...
2021-04-19T15:41:21.7354436Z Starting Internet Information Server
2021-04-19T15:41:23.2028588Z Copying Service Tier Files
2021-04-19T15:41:24.7110460Z Copying PowerShell Scripts
2021-04-19T15:41:24.7127051Z Copying dependencies
2021-04-19T15:41:24.7144208Z Copying ReportBuilder
2021-04-19T15:41:24.7159689Z Importing PowerShell Modules
2021-04-19T15:41:42.1539351Z Determining Database Collation from c:\dl\sandbox\19.0.24563.0\us\BusinessCentral-US.bak
2021-04-19T15:42:18.7411232Z Restoring CRONUS Demo Database
2021-04-19T15:42:20.1991877Z Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
2021-04-19T15:46:21.0770740Z Exporting Application to CRONUS
2021-04-19T15:46:34.6356979Z Removing Application from tenant
2021-04-19T15:46:34.6370775Z Modifying Business Central Service Tier Config File for Docker
2021-04-19T15:46:34.6386341Z Creating Business Central Service Tier
2021-04-19T15:46:36.1102531Z Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
2021-04-19T15:46:36.1116996Z Copying Web Client Files
2021-04-19T15:46:36.1131318Z Copying Client Files
2021-04-19T15:46:36.1157926Z Copying ModernDev Files
2021-04-19T15:46:36.1170627Z Copying additional files
2021-04-19T15:46:36.1187324Z Copying ConfigurationPackages
2021-04-19T15:46:36.1200581Z Copying Test Assemblies
2021-04-19T15:46:36.1214638Z Copying Extensions
2021-04-19T15:46:36.1228689Z Copying Applications
2021-04-19T15:46:36.1243372Z Copying Applications.US
2021-04-19T15:46:53.3322221Z Starting Business Central Service Tier
2021-04-19T15:46:54.7822851Z Importing license file
2021-04-19T15:46:54.7837212Z Copying Database on localhost\SQLEXPRESS from tenant to default
2021-04-19T15:46:56.6273174Z Taking database tenant offline
2021-04-19T15:47:00.8499783Z Copying database files
2021-04-19T15:47:17.8302661Z Attaching files as new Database default
2021-04-19T15:47:17.8317120Z Putting database tenant back online
2021-04-19T15:47:17.8332324Z Mounting tenant database
2021-04-19T15:50:08.6733909Z Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
2021-04-19T15:50:08.6748405Z Sync'ing Tenant
2021-04-19T15:50:08.6763115Z Tenant is Operational
2021-04-19T15:50:08.6777618Z Stopping Business Central Service Tier
2021-04-19T15:50:08.6791982Z Installation took 558 seconds
2021-04-19T15:50:08.6806230Z Installation complete
2021-04-19T15:50:10.1240539Z Initializing...
2021-04-19T15:50:10.1253644Z Setting host.containerhelper.internal to 172.19.160.1 in container hosts file
2021-04-19T15:50:10.1266289Z Starting Container
2021-04-19T15:50:10.1279079Z Hostname is devops2-SWE-nextmajor
2021-04-19T15:50:11.5850682Z PublicDnsName is devops2-SWE-nextmajor
2021-04-19T15:50:13.0387294Z Using NavUserPassword Authentication
2021-04-19T15:50:15.9595127Z Creating Self Signed Certificate
2021-04-19T15:50:15.9608688Z Self Signed Certificate Thumbprint 35F0FCEC7DBB1036E07B1490AAB65D7E7E547AD0
2021-04-19T15:50:15.9622247Z Modifying Service Tier Config File with Instance Specific Settings
2021-04-19T15:50:15.9636425Z Modifying Service Tier Config File with settings from environment variable
2021-04-19T15:50:17.3660628Z Setting EnableTaskScheduler to False
2021-04-19T15:50:29.5235638Z Starting Service Tier
2021-04-19T15:50:29.5247233Z Registering event sources
2021-04-19T15:50:40.2097677Z Creating DotNetCore Web Server Instance
2021-04-19T15:50:40.2109787Z Enabling Financials User Experience
2021-04-19T15:50:40.2122562Z Enabling rewrite rule: Don't rewrite system files
2021-04-19T15:50:40.2134286Z Enabling rewrite rule: Already have tenant specified
2021-04-19T15:50:40.2145930Z Enabling rewrite rule: Hostname (without port) to tenant
2021-04-19T15:50:40.2160263Z Using license file 'c:\run\my\license.flf'
2021-04-19T15:50:43.0436407Z Import License
2021-04-19T15:50:43.0448869Z Dismounting Tenant
2021-04-19T15:50:43.0462027Z Mounting Tenant
2021-04-19T15:51:07.6389995Z Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
2021-04-19T15:51:07.6403224Z Sync'ing Tenant
2021-04-19T15:51:07.6417041Z Tenant is Operational
2021-04-19T15:51:09.0968479Z Creating http download site
2021-04-19T15:51:09.0982912Z Setting SA Password and enabling SA
2021-04-19T15:51:10.5572568Z Creating admin as SQL User and add to sysadmin
2021-04-19T15:51:25.9560016Z Creating SUPER user
2021-04-19T15:51:25.9574921Z Container IP Address: 172.19.167.195
2021-04-19T15:51:25.9587605Z Container Hostname  : devops2-SWE-nextmajor
2021-04-19T15:51:25.9601619Z Container Dns Name  : devops2-SWE-nextmajor
2021-04-19T15:51:25.9615414Z Web Client          : http://devops2-SWE-nextmajor/BC/?tenant=default
2021-04-19T15:51:25.9629168Z Dev. Server         : http://devops2-SWE-nextmajor
2021-04-19T15:51:25.9642988Z Dev. ServerInstance : BC
2021-04-19T15:51:25.9656912Z Dev. Server Tenant  : default
2021-04-19T15:51:25.9672804Z Setting devops2-SWE-nextmajor to 172.19.167.195 in host hosts file
2021-04-19T15:51:25.9686926Z Setting devops2-SWE-nextmajor-default to 172.19.167.195 in host hosts file
2021-04-19T15:51:25.9701192Z Setting devops2-SWE-nextmajor-default to 172.19.167.195 in container hosts file
2021-04-19T15:51:25.9709460Z 
2021-04-19T15:51:25.9723212Z Files:
2021-04-19T15:51:25.9736948Z http://devops2-SWE-nextmajor:8080/ALLanguage.vsix
2021-04-19T15:51:25.9744158Z 
2021-04-19T15:51:25.9757868Z Container Total Physical Memory is 12.0Gb
2021-04-19T15:51:25.9771681Z Container Free Physical Memory is 6.1Gb
2021-04-19T15:51:25.9778591Z 
2021-04-19T15:51:25.9792004Z Initialization took 77 seconds
2021-04-19T15:51:25.9805534Z Ready for connections!
2021-04-19T15:51:25.9819324Z Reading CustomSettings.config from devops2-SWE-nextmajor
2021-04-19T15:51:29.8303496Z Creating Desktop Shortcuts for devops2-SWE-nextmajor
2021-04-19T15:51:30.6878518Z Container devops2-SWE-nextmajor successfully created
2021-04-19T15:51:30.6887164Z 
2021-04-19T15:51:30.6901696Z Use:
2021-04-19T15:51:30.6922476Z Get-BcContainerEventLog -containerName devops2-SWE-nextmajor to retrieve a snapshot of the event log from the container
2021-04-19T15:51:30.6948411Z Get-BcContainerDebugInfo -containerName devops2-SWE-nextmajor to get debug information about the container
2021-04-19T15:51:30.6973744Z Enter-BcContainer -containerName devops2-SWE-nextmajor to open a PowerShell prompt inside the container
2021-04-19T15:51:30.6999292Z Remove-BcContainer -containerName devops2-SWE-nextmajor to remove the container again
2021-04-19T15:51:30.7027439Z docker logs devops2-SWE-nextmajor to retrieve information about URL's again
2021-04-19T15:51:30.7322768Z 
2021-04-19T15:51:30.7344691Z Creating container took 671 seconds
2021-04-19T15:51:30.7353776Z 
2021-04-19T15:51:30.7370621Z   _____           _        _ _ _                                     
2021-04-19T15:51:30.7386706Z  |_   _|         | |      | | (_)                                    
2021-04-19T15:51:30.7402749Z    | |  _ __  ___| |_ __ _| | |_ _ __   __ _    __ _ _ __  _ __  ___ 
2021-04-19T15:51:30.7418354Z    | | | '_ \/ __| __/ _` | | | | '_ \ / _` |  / _` | '_ \| '_ \/ __|
2021-04-19T15:51:30.7434453Z   _| |_| | | \__ \ |_ (_| | | | | | | | (_| | | (_| | |_) | |_) \__ \
2021-04-19T15:51:30.7450755Z  |_____|_| |_|___/\__\__,_|_|_|_|_| |_|\__, |  \__,_| .__/| .__/|___/
2021-04-19T15:51:30.7466695Z                                         __/ |       | |   | |        
2021-04-19T15:51:30.7482661Z                                        |___/        |_|   |_|        
2021-04-19T15:51:30.7494072Z 
2021-04-19T15:51:33.9639558Z Publishing C:\ProgramData\BcContainerHelper\Extensions\devops2-SWE-nextmajor\80019041-b1c9-4512-a849-4dc077e16d14\Insight Works_IWorks Common_2.4.7674.0_runtime 18.0.app
2021-04-19T15:51:34.6053689Z WARNING: UnhandledErrorMessage
2021-04-19T15:51:34.7108296Z Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
2021-04-19T15:51:34.7149502Z at <ScriptBlock>, <No file>: line 18
2021-04-19T15:51:34.7182336Z at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11-preview422\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
2021-04-19T15:51:34.7201013Z at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11-preview422\AppHandling\Publish-NavContainerApp.ps1: line 257
2021-04-19T15:51:34.7220565Z at Publish-BcContainerApp, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11-preview422\AppHandling\Publish-NavContainerApp.ps1: line 117
2021-04-19T15:51:34.7238384Z at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11-preview422\AppHandling\Run-AlPipeline.ps1: line 506
2021-04-19T15:51:34.7254530Z at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11-preview422\AppHandling\Run-AlPipeline.ps1: line 738
2021-04-19T15:51:34.7270699Z at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11-preview422\AppHandling\Run-AlPipeline.ps1: line 707
2021-04-19T15:51:34.7290709Z at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11-preview422\AppHandling\Run-AlPipeline.ps1: line 701
2021-04-19T15:51:34.7306582Z at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11-preview422\AppHandling\Run-AlPipeline.ps1: line 577
2021-04-19T15:51:34.7321277Z at Run-AlPipeline, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11-preview422\AppHandling\Run-AlPipeline.ps1: line 544
2021-04-19T15:51:34.7333295Z at <ScriptBlock>, C:\Agent\_work\24\s\DevOpsBCScripts\DevOps-Pipeline.ps1: line 121
2021-04-19T15:51:34.7346696Z at <ScriptBlock>, C:\Agent\_work\_temp\35d353da-7e3f-4b71-b5e9-090822f52202.ps1: line 3
2021-04-19T15:51:34.7359330Z at <ScriptBlock>, <No file>: line 1
2021-04-19T15:51:34.8290931Z 
2021-04-19T15:51:34.8306904Z   _____                           _                _____            _        _                 
2021-04-19T15:51:34.8321784Z  |  __ \                         (_)              / ____|          | |      (_)                
2021-04-19T15:51:34.8335623Z  | |__) |___ _ __ ___   _____   ___ _ __   __ _  | |     ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
2021-04-19T15:51:34.8350438Z  |  _  // _ \ '_ ` _ \ / _ \ \ / / | '_ \ / _` | | |    / _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
2021-04-19T15:51:34.8364520Z  | | \ \  __/ | | | | | (_) \ V /| | | | | (_| | | |____ (_) | | | | |_ (_| | | | | |  __/ |   
2021-04-19T15:51:34.8379467Z  |_|  \_\___|_| |_| |_|\___/ \_/ |_|_| |_|\__, |  \_____\___/|_| |_|\__\__,_|_|_| |_|\___|_|   
2021-04-19T15:51:34.8393415Z                                            __/ |                                               
2021-04-19T15:51:34.8411364Z                                           |___/                                                
2021-04-19T15:51:34.8420461Z 
2021-04-19T15:51:37.5570250Z Removing container devops2-SWE-nextmajor
2021-04-19T15:51:43.4309275Z Removing devops2-SWE-nextmajor from container hosts file
2021-04-19T15:51:43.7222518Z Removing devops2-SWE-nextmajor-* from container hosts file
2021-04-19T15:51:43.7944716Z Removing C:\ProgramData\BcContainerHelper\Extensions\devops2-SWE-nextmajor
2021-04-19T15:51:43.8891194Z 
2021-04-19T15:51:43.8908013Z Removing container took 9 seconds
2021-04-19T15:51:44.6209925Z ##[error]Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' 
or one of its dependencies. The system cannot find the file specified.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11-preview422\ContainerHandling\Invoke-ScriptInNavC
ontainer.ps1:45 char:13
+             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not load ...file specified.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, Pub 
   licKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
2021-04-19T15:51:44.6446772Z ##[error]PowerShell exited with code '1'.
2021-04-19T15:51:44.7214316Z ##[section]Finishing: Run Pipeline

**Comment by freddydk** [comment]
This app: C:\ProgramData\BcContainerHelper\Extensions\devops2-SWE-nextmajor\80019041-b1c9-4512-a849-4dc077e16d14\Insight Works_IWorks Common_2.4.7674.0_runtime 18.0.app

Seems to be an 18.0 runtime package.
runtime packages are very strictly tied to the version they are created and/or installed on.

You will need a 19.0 runtime package for nextmajor now.

**Comment by MatthewMcCarthy7** [comment]
Thank you that was the issue.
