### ISSUE TITLE
Templates Down

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/navcontainerhelper#3471]
**Describe the issue**
Navigating to https://aka.ms/getbcext or https://aka.ms/getbc results in an error.

There was an error downloading the template from URI 'https://freddyk.azurewebsites.net/api/MergeArmTemplate'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. 

**Screenshots**
![image](https://github.com/microsoft/navcontainerhelper/assets/16603906/f62607fe-d600-4e25-a400-675e29a463dc)

**Additional context**
- does it happen all the time? Yes
- did it use to work? Yes

**Comment by freddydk** [comment]
Looks like this was a transient or local error - it works now (from here).
Could you check again?

**Comment by freddydk** [comment]
Just tried to create a VM end 2 end - works fine with the new artifact CDN as well
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/e4d3e38f-b9ad-405c-9e5d-8c8c93070614)

**Comment by mjmatthiesen** [comment]
I am still experiencing the same issue. Others on my team are as well. Might be a stupid question, but is this something IT could've limited through some policy or something?

![image](https://github.com/microsoft/navcontainerhelper/assets/16603906/e2d76ed8-e08d-40cd-8f6b-e4041b0d17b3)



https://github.com/microsoft/navcontainerhelper/assets/16603906/39f55343-a061-4fb4-a2db-dd5f768ac343

**Comment by freddydk** [comment]
Got it - looks like the redirect order has changed in the azure portal (sometimes - maybe when authentication expired) - I have modified the CORS policy accordingly, should work now.

**Comment by mjmatthiesen** [comment]
I'm still experiencing the same. Tried my work and personal account, as well as on my personal machine. Shouldn't have an impact, but just in case.

If there's something else I can test or look into, please let me know.

**Comment by freddydk** [comment]
Did you try to remove cookies etc.?

**Comment by freddydk** [comment]
the aka.ms/getbc is really just calling an azure function, which redirects you to the URL above (with the parameters specified)

**Comment by mjmatthiesen** [comment]
Tried it incognito and the other machine I tried it on has never been logged into an MS account before. I don't think many people are creating right now, or like me, probably reuse the same VM for a while. So far I've only seen one person report it on yammer.

https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=2744812438462464

**Comment by freddydk** [comment]
What happens if you open this in a browser on your machine

```
https://freddyk.azurewebsites.net/api/MergeArmTemplate/?templatename=getbc&template=https%3A%2F%2Fraw.githubusercontent.com%2FMicrosoft%2Fnav-arm-templates%2Fmaster%2Fgetbc.json
``´

**Comment by mjmatthiesen** [comment]
I can confirm that they are working again. Thank you for the prompt resolution.
